name: mobile_mad3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/src/assets/logos/google_logo.svg
    - lib/src/assets/logos/facebook_logo.svg
    - lib/src/assets/logos/twitter_logo.svg
