// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu0Lp8E2L-g9KK2wNyNnfDyReHrixPC3c',
    appId: '1:800502284406:web:eb735f88e405aa7502df57',
    messagingSenderId: '800502284406',
    projectId: 'mobile-mad3-2ac10',
    authDomain: 'mobile-mad3-2ac10.firebaseapp.com',
    storageBucket: 'mobile-mad3-2ac10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkrlmU0862RuqIOc8V6US6irRiArP7B3A',
    appId: '1:800502284406:android:757ed5dac5e9aca602df57',
    messagingSenderId: '800502284406',
    projectId: 'mobile-mad3-2ac10',
    storageBucket: 'mobile-mad3-2ac10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD96Io0JKWchdlzE9-XBMON8AuY92jai44',
    appId: '1:800502284406:ios:42d93ed44f316c8702df57',
    messagingSenderId: '800502284406',
    projectId: 'mobile-mad3-2ac10',
    storageBucket: 'mobile-mad3-2ac10.appspot.com',
    iosBundleId: 'com.example.mobileMad3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD96Io0JKWchdlzE9-XBMON8AuY92jai44',
    appId: '1:800502284406:ios:42d93ed44f316c8702df57',
    messagingSenderId: '800502284406',
    projectId: 'mobile-mad3-2ac10',
    storageBucket: 'mobile-mad3-2ac10.appspot.com',
    iosBundleId: 'com.example.mobileMad3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu0Lp8E2L-g9KK2wNyNnfDyReHrixPC3c',
    appId: '1:800502284406:web:070cfdc299fc05c902df57',
    messagingSenderId: '800502284406',
    projectId: 'mobile-mad3-2ac10',
    authDomain: 'mobile-mad3-2ac10.firebaseapp.com',
    storageBucket: 'mobile-mad3-2ac10.appspot.com',
  );
}
